<?php

declare(strict_types=1);

namespace Pynarae\Verify\Console\Command;

use Magento\Framework\Console\Cli;
use Pynarae\Verify\Model\QrSvgGenerator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class ExportQrImagesCommand extends Command
{
    public function __construct(
        private QrSvgGenerator $qrSvgGenerator,
        ?string $name = null
    ) {
        parent::__construct($name);
    }

    protected function configure(): void
    {
        $this->setName('pynarae:verify:export-qr-images')
            ->setDescription('Offline batch generate QR SVG images from CSV')
            ->addOption('input', null, InputOption::VALUE_REQUIRED, 'Input CSV path generated by generate-csv')
            ->addOption('output-dir', null, InputOption::VALUE_REQUIRED, 'Output directory for QR SVG files')
            ->addOption('url-column', null, InputOption::VALUE_OPTIONAL, 'CSV column containing URL payload', 'verify_url')
            ->addOption('name-column', null, InputOption::VALUE_OPTIONAL, 'CSV column for output filename', 'code')
            ->addOption('size', null, InputOption::VALUE_OPTIONAL, 'QR size in px', '300')
            ->addOption('margin', null, InputOption::VALUE_OPTIONAL, 'QR margin', '2');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $inputFile = trim((string)$input->getOption('input'));
        $outputDir = trim((string)$input->getOption('output-dir'));
        $urlColumn = trim((string)$input->getOption('url-column'));
        $nameColumn = trim((string)$input->getOption('name-column'));
        $size = max(80, (int)$input->getOption('size'));
        $margin = max(0, (int)$input->getOption('margin'));

        if ($inputFile === '' || !is_file($inputFile) || !is_readable($inputFile)) {
            $output->writeln('<error>Input CSV not found or unreadable.</error>');
            return Cli::RETURN_FAILURE;
        }

        if ($outputDir === '') {
            $output->writeln('<error>The --output-dir option is required.</error>');
            return Cli::RETURN_FAILURE;
        }

        if (!is_dir($outputDir) && !@mkdir($outputDir, 0775, true) && !is_dir($outputDir)) {
            $output->writeln('<error>Could not create output directory.</error>');
            return Cli::RETURN_FAILURE;
        }

        $handle = fopen($inputFile, 'rb');
        if ($handle === false) {
            $output->writeln('<error>Could not open input CSV.</error>');
            return Cli::RETURN_FAILURE;
        }

        $header = fgetcsv($handle);
        if (!is_array($header)) {
            fclose($handle);
            $output->writeln('<error>Input CSV header is missing.</error>');
            return Cli::RETURN_FAILURE;
        }

        $headerMap = [];
        foreach ($header as $idx => $name) {
            $headerMap[trim((string)$name)] = $idx;
        }

        if (!isset($headerMap[$urlColumn])) {
            fclose($handle);
            $output->writeln(sprintf('<error>CSV column "%s" not found.</error>', $urlColumn));
            return Cli::RETURN_FAILURE;
        }

        if (!isset($headerMap[$nameColumn])) {
            fclose($handle);
            $output->writeln(sprintf('<error>CSV column "%s" not found.</error>', $nameColumn));
            return Cli::RETURN_FAILURE;
        }

        $generated = 0;
        while (($row = fgetcsv($handle)) !== false) {
            $url = trim((string)($row[$headerMap[$urlColumn]] ?? ''));
            $name = trim((string)($row[$headerMap[$nameColumn]] ?? ''));

            if ($url === '' || $name === '') {
                continue;
            }

            $safeName = preg_replace('/[^A-Za-z0-9\-_]/', '_', $name) ?: 'qr_' . ($generated + 1);
            $svg = $this->qrSvgGenerator->generate($url, $size, $margin);
            file_put_contents(rtrim($outputDir, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . $safeName . '.svg', $svg);
            $generated++;
        }

        fclose($handle);
        $output->writeln(sprintf('<info>Generated %d QR image(s) into %s</info>', $generated, $outputDir));

        return Cli::RETURN_SUCCESS;
    }
}
